[network]
name = "mainnet"
stacks_node_rpc_address = "https://stacks-node-api.stacks.co"
stacks_node_p2p_address = "https://stacks-node-api.stacks.co"
stacks_node_event_source_address = "https://stacks-node-api.stacks.co"
chain_id = 1
