[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "paper venue rotate loud blade gossip chunk peanut universe duck picture found jeans wall defense ridge net genuine seat fantasy assume dawn team chronic"
balance = 10000000
