[network]
name = "testnet"
stacks_node_rpc_address = "https://stacks-node-api.stacks-testnet.com"
stacks_node_p2p_address = "https://stacks-node-api.stacks-testnet.com"
stacks_node_event_source_address = "https://stacks-node-api.stacks-testnet.com"
chain_id = 2147483648
